### ISSUE TITLE
Setup deno project to make use of hubble-bls signer.ts

### ISSUE THREAD

**Issue by jzaki** [jzaki/bls-wallet-signer#1]
[BLSSignerFactor](https://github.com/thehubbleproject/hubble-bls/blob/master/src/signer.ts) part of hubble-bls module.

Usage example, [here](https://github.com/jzaki/bls-wallet/blob/main/test/verificationGateway-test.ts#L48).

**Comment by voltrevo** [comment]
Here you go: https://github.com/jzaki/bls-signer/pull/3
